// autogenerated on build by applying crc32 on the concatenation of log_format.h and sensor_data.h
// source can be found at https://github.com/ISSUIUC/MIDAS-Software/tree/75bbefd9edda77f654b88370ef6c978b90b8637
#define LOG_CHECKSUM (0x4d93b556)
