"""
SUSTAINER TRANSITIONS
"""
SUSTAINER_IDLE_TO_FIRST_BOOST_ACCELERATION_THRESHOLD = 3

SUSTAINER_IDLE_TO_FIRST_BOOST_TIME_THRESHOLD = 1000

SUSTAINER_IGNITION_TO_SECOND_BOOST_ACCELERATION_THRESHOLD = 3

SUSTAINER_SECOND_BOOST_TO_COAST_TIME_THRESHOLD = 1000

SUSTAINER_COAST_DETECTION_ACCELERATION_THRESHOLD = 0.2

SUSTAINER_COAST_TO_APOGEE_VERTICAL_SPEED_THRESHOLD = 15

SUSTAINER_APOGEE_BACKTO_COAST_VERTICAL_SPEED_THRESHOLD = 10

SUSTAINER_APOGEE_CHECK_THRESHOLD = 1000

SUSTAINER_APOGEE_TIMER_THRESHOLD = 1000

SUSTAINER_DROGUE_TIMER_THRESHOLD = 3000

SUSTAINER_MAIN_TO_MAIN_DEPLOY_TIMER_THRESHOLD = 3000

SUSTAINER_MAIN_DEPLOY_ALTITUDE_THRESHOLD = 3000

SUSTAINER_IGNITION_TO_SECOND_BOOST_TIME_THRESHOLD = 1000

SUSTAINER_IGNITION_TO_COAST_TIMER_THRESHOLD = 5000

SUSTAINER_LANDED_TIMER_THRESHOLD = 5000

SUSTAINER_FIRST_BOOST_TO_BURNOUT_TIME_THRESHOLD = 1000

SUSTAINER_LANDED_VERTICAL_SPEED_THRESHOLD = 20

SUSTAINER_DROGUE_JERK_THRESHOLD = 200

SUSTAINER_MAIN_JERK_THRESHOLD = 300

"""
BOOSTER TRANSITIONS
"""
BOOSTER_IDLE_TO_FIRST_BOOST_ACCELERATION_THRESHOLD = 3

BOOSTER_IDLE_TO_FIRST_BOOST_TIME_THRESHOLD = 1000

BOOSTER_FIRST_SEPERATION_TIME_THRESHOLD = 3000

BOOSTER_COAST_DETECTION_ACCELERATION_THRESHOLD = 0.2

BOOSTER_COAST_TO_APOGEE_VERTICAL_SPEED_THRESHOLD = 20

BOOSTER_APOGEE_CHECK_THRESHOLD = 1000

BOOSTER_APOGEE_TIMER_THRESHOLD = 1000

BOOSTER_DROGUE_TIMER_THRESHOLD = 3000

BOOSTER_MAIN_TO_MAIN_DEPLOY_TIMER_THRESHOLD = 3000

BOOSTER_MAIN_DEPLOY_ALTITUDE_THRESHOLD = 3000
BOOSTER_IGNITION_TO_SECOND_BOOST_TIME_THRESHOLD = 1000

BOOSTER_IGNITION_TO_COAST_TIMER_THRESHOLD = 5000

BOOSTER_LANDED_TIMER_THRESHOLD = 5000

BOOSTER_FIRST_BOOST_TO_BURNOUT_TIME_THRESHOLD = 1000

BOOSTER_LANDED_VERTICAL_SPEED_THRESHOLD = 20

BOOSTER_FIRST_SEPARATION_JERK_THRESHOLD = 300

BOOSTER_DROGUE_JERK_THRESHOLD = 200

BOOSTER_MAIN_JERK_THRESHOLD = 300
