import subprocess
import sys
import zlib
from pathlib import Path

assert sys.version_info >= (3, 5)

Import("env")

eeprom_format_text = (Path("src/feather_duo") / "esp_eeprom_format.h").read_text()

git_command = ["git", "log", "-n", "1", "--pretty=format:%H"]
git_hash = subprocess.run(git_command, stdout=subprocess.PIPE).stdout.decode('utf-8')
git_hash = git_hash[:-1]  # get rid of trailing new line

checksum_eeprom = zlib.crc32(eeprom_format_text.encode("utf-8"))

file_eeprom = f"""\
// autogenerated on build by applying crc32 on esp_eeprom_format.h
#define EEPROM_CHECKSUM (0x{checksum_eeprom:08x})
"""

with Path("src/feather_duo/esp_eeprom_checksum.h").open("w") as checksum_file_eeprom:
    checksum_file_eeprom.write(file_eeprom)
