import sys
import zlib
from pathlib import Path

assert sys.version_info >= (3, 5)

Import("env")

log_format_text = (Path("src") / "log_format.h").read_text()
sensor_data_text = (Path("src") / "sensor_data.h").read_text()

checksum = zlib.crc32((log_format_text + sensor_data_text).encode("utf-8"))

file = f"""\
// autogenerated on build by applying crc32 on the concatenation of log_format.h and sensor_data.h
#define LOG_CHECKSUM (0x{checksum:08x})
"""

with Path("src/log_checksum.h").open("w") as checksum_file:
    checksum_file.write(file)
