; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
test_ignore = fsm_test

[env:mcu_main]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
extra_scripts =
    pre:tools/extra_script.py
    pre:tools/log_enc.py
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_DISABLE_HAL_LOCKS=1
    -std=gnu++2a
build_unflags =
    -std=gnu++11
    -DARDUINO_USB_MODE=1
lib_deps =
    adafruit/Adafruit LIS3MDL@^1.2.1 ; Old magnetometer driver, Adafruit_BNO08x fails or else
    sparkfun/SparkFun MMC5983MA Magnetometer Arduino Library@^1.1.4 ; Magnetometer driver
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8 ; GPS

build_src_filter = +<*> -<silsim/> +<hardware/> -<hilsim> -<log_decode/>

[env:mcu_hilsim]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = 
	pre:tools/extra_script.py
    pre:tools/log_enc.py
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DHILSIM=1
	-std=gnu++2a
build_src_filter = +<*> -<silsim/> -<hardware/> +<hilsim> -<log_decode/> -<hilsim/stream> +<hardware/Pyro.cpp> +<hardware/SDLog.cpp> +<hardware/Voltage.cpp> -<hilsim/sensors/Voltage.cpp>
build_unflags = 
	-std=gnu++11
lib_deps = sparkfun/SparkFun MMC5983MA Magnetometer Arduino Library@^1.1.4

[env:native_hilsim_streamer]
platform = native
build_type = debug
lib_archive = no
extra_scripts =
    pre:tools/extra_script.py
build_flags =
    -g3
    -std=gnu++17
    -pthread
    -Isrc/hilsim/stream
build_src_filter = +<hilsim/stream/**/*.cpp> -<hardware/> -<silsim>
build_unflags =
    -std=gnu++03
    -std=gnu++11
    -std=gnu++14
    -std=c++03
    -std=c++11 
    -std=c++14

[env:native_hilsim_streamer_debug]
platform = native
build_type = debug
lib_archive = no
extra_scripts =
    pre:extra_script.py
build_flags =
    -g3
    -std=gnu++17
    -DDEBUG
    -pthread
    -Isrc/hilsim/stream
build_src_filter = +<hilsim/stream/**/*.cpp> -<hardware/> -<silsim>
build_unflags =
    -std=gnu++03
    -std=gnu++11
    -std=gnu++14
    -std=c++03
    -std=c++11 
    -std=c++14
    

[env:mcu_silsim_sustainer]
platform = native
build_type = debug
extra_scripts = 
	pre:tools/extra_script.py
build_flags = 
	-DSILSIM
	-g3
	-std=gnu++2a
build_src_filter = +<*> +<silsim/**/*.cpp> -<hardware/> -<hilsim> -<log_decode/>
build_unflags = 
	-std=gnu++11
lib_deps = sparkfun/SparkFun MMC5983MA Magnetometer Arduino Library@^1.1.4

[env:fsm_sim]
platform = native
build_type = debug
build_flags =
    -DSILSIM
    -DFSM_SIMULATOR
    -std=gnu++2a
    -Isrc
    -Isrc/finite-state-machines
    -Ilib/CRCpp
    -Itest/fsm_test/src
build_unflags =
    -std=gnu++11
build_src_filter =
    -<*>
    +<finite-state-machines/fsm.cpp>
extra_scripts = pre:test/fsm_test/srcinc.py

[env:mcu_silsim_booster]
platform = native
build_type = debug
extra_scripts = 
	pre:tools/extra_script.py
build_flags = 
	-DSILSIM
	-g3
	-std=gnu++2a
build_src_filter = +<*> +<silsim/**/*.cpp> -<hardware/> -<hilsim> -<log_decode/>
build_unflags =
    -std=gnu++11
lib_deps =
    Eigen
lib_ignore =
    TCAL9539
