name: Deploy documentation
# If I graduate or die in a horrific accident, and you need to setup a new SSH key, follow these instructions:
# https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys
# You probably need write access to MIDAS-flight-docs and need to write the SSH key to the MIDAS repo.
on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
  
    - name: Create Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: './MIDAS/docs'

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY : ${{ secrets.SSH_DEPLOY_KEY  }}
      with:
        source-directory: 'MIDAS/docs/html'
        destination-github-username: ISSUIUC
        destination-repository-name: MIDAS-flight-docs
        user-email: action@github.com
        target-branch: main
        target-directory: docs
